min_fdmc: 100000 # Minimum USD of the token fully diluted market cap
max_fdmc: 1000000 # Maximum USD of the token fully diluted market cap
max_token_share: 30 # Maximum share percentage of the total supply which an address can hold
output_path: "output.csv" # The output .csv file